Reading Datasets

In [13]:
import pandas as pd
confirmed=pd.read_csv("../../../../data/stage_1/covid_confirmed_usafacts.csv")
population=pd.read_csv("../../../../data/stage_1/covid_county_population_usafacts.csv")
deaths=pd.read_csv("../../../../data/stage_1/covid_deaths_usafacts.csv")


confirmed_cases=pd.DataFrame(confirmed)
population_county=pd.DataFrame(population)
death_count=pd.DataFrame(deaths)

In [14]:
confirmed_cases

,countyFIPS,County Name,State,StateFIPS,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,...,8/7/2021,8/8/2021,8/9/2021,8/10/2021,8/11/2021,8/12/2021,8/13/2021,8/14/2021,8/15/2021,8/16/2021
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,7694,7694,7788,7818,7854,7890,7931,7931,7931,8061
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,26822,26822,27477,27736,28020,28358,28629,28629,28629,29234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,2585,2585,2629,2649,2681,2699,2732,2732,2732,2761
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,2973,2973,3016,3034,3056,3069,3095,3095,3095,3129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,5056,5056,5056,5090,5090,5108,5114,5127,5127,5127
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,3960,3960,3960,4003,4003,4014,4044,4068,4068,4068
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,2498,2498,2498,2538,2538,2543,2559,2593,2593,2593
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,950,950,950,958,958,960,968,967,967,967
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,694,694,694,699,699,700,700,705,705,705

In [15]:
population_county

      countyFIPS            County Name State  population
0              0  Statewide Unallocated    AL           0
1           1001         Autauga County    AL       55869
2           1003         Baldwin County    AL      223234
3           1005         Barbour County    AL       24686
4           1007            Bibb County    AL       22394
...          ...                    ...   ...         ...
3190       56037      Sweetwater County    WY       42343
3191       56039           Teton County    WY       23464
3192       56041           Uinta County    WY       20226
3193       56043        Washakie County    WY        7805
3194       56045          Weston County    WY        6927

[3195 rows x 4 columns]

In [16]:
death_count

,countyFIPS,County Name,State,StateFIPS,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,...,8/7/2021,8/8/2021,8/9/2021,8/10/2021,8/11/2021,8/12/2021,8/13/2021,8/14/2021,8/15/2021,8/16/2021
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,114,114,114,114,114,114,114,114,114,114
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,330,330,330,332,338,342,344,344,344,347
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,63,63,63,63,64,64,65,65,65,65
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,66,66,66,66,67,67,67,67,67,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,45,45,45,45,45,45,45,45,45,45
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,11,11,11,11,11,11,11,11,11,11
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,14,14,14,14,14,14,14,14,14,14
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,26,26,26,26,26,26,26,26,26,26
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,6,6

Merging all datasets into a super dataset

In [17]:
merge_1=pd.merge(confirmed_cases,death_count,on=['countyFIPS','County Name','State','StateFIPS'])
merge_1.dtypes
merge_2=pd.merge(population_county,merge_1,on=['countyFIPS','State'])

Saving the superset dataframe to .csv file

In [10]:
merge_2.to_csv("../../../../data/stage_1/superset.csv",index=False)